api: 0.0.0.0:5279
streaming_server: 0.0.0.0:5280

components_to_skip:
- hash_announcer
- blob_server
- dht
- stream_identifier
- payment_rate_manager
- exchange_rate_manager
- reflector
track_bandwidth: false
share_usage_data: false

data_dir: /storage/lbrynet
download_dir: /storage/download
wallet_dir: /storage/lbryum

save_blobs: false
save_files: false
share_usage_data: false
use_upnp: false
save_resolved_claims: false

reflect_streams: false

# known_dht_nodes:
#   - 127.0.0.1:4444

lbryum_servers:
  - s1.lbry.network:50001
  # - hub.lbry.nl:50001